#!/bin/bash
set -e

export CC=$(which arm-linux-gnueabihf-gcc)
export CXX="$(which arm-linux-gnueabihf-g++) --sysroot=$(pwd)/rootfs -L$(pwd)/rootfs/usr/lib/arm-linux-gnueabihf/"

cd vscode
cp -v ../product.json .
cp -v ../code.png resources/linux
./scripts/npm.sh install --arch=arm
gulp vscode-linux-arm-min --max_old_space_size=4096
gulp vscode-linux-arm-build-deb
cd ..
cp -v vscode/.build/linux/deb/armhf/deb/*.deb .
