#!/bin/bash
set -e

export CC="$(which arm-linux-gnueabihf-gcc)"
export CXX="$(which arm-linux-gnueabihf-g++) --sysroot=$(pwd)/rootfs -L$(pwd)/rootfs/usr/lib/arm-linux-gnueabihf -I$(pwd)/rootfs/usr/include/libsecret-1 -I$(pwd)/rootfs/usr/include/glib-2.0 -I$(pwd)/rootfs/usr/lib/arm-linux-gnueabihf/glib-2.0/include"
export PKG_CONFIG_PATH="$(pwd)/rootfs/usr/share/pkgconfig:$(pwd)/rootfs/usr/lib/arm-linux-gnueabihf/pkgconfig"
export npm_config_target="$(grep target vscode/.yarnrc | sed 's/[^0-9.]*//g')"

cd vscode
cp -rv ../resources/app/* .
sed -i 's/.*darwinCredits.*//' product.json
sed -i 's/.*electronRepository.*//' product.json

echo > build/npm/preinstall.js
npm install --target_arch=arm
yarn run gulp vscode-linux-arm-min
yarn run gulp vscode-linux-arm-build-deb
cd ..
cp -v vscode/.build/linux/deb/armhf/deb/*.deb .
