#!/bin/bash
set -e

export CC=$(which arm-linux-gnueabihf-gcc)
export CXX="$(which arm-linux-gnueabihf-g++) -L$(pwd)/rootfs/usr/lib/arm-linux-gnueabihf/"

cd vscode
git fetch --tags
git checkout 1.11.0
cp -v ../product.json .
cp -v ../code.png resources/linux
scripts/npm.sh install --arch=armhf
gulp vscode-linux-arm-build-deb
cd ..

cp -v vscode/.build/linux/deb/armhf/deb/*.deb .
