#!/bin/bash
set -e

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get dist-upgrade -y
sudo apt-get install -y git build-essential nodejs g++ libx11-dev libxkbfile-dev debootstrap qemu-user-static python fakeroot rpm
sudo npm install -g gulp
git clone git@github.com:microsoft/vscode || true
git fetch
git checkout 1.10.2
sudo qemu-debootstrap --arch=armhf --variant=minbase xenial rootfs
sudo chroot rootfs apt-get update
sudo chroot rootfs apt-get dist-upgrade -y
sudo chroot rootfs apt-get install -y libx11-dev libxkbfile-dev
